// Visual workflow only. Reloading restores the fictional sample data.
const $=s=>document.querySelector(s);
let projects=[{id:'strawberry',title:'קצת תותים. הרבה שמחה.',description:'דמיינתי חגיגה שכולה תותים: קופסאות קטנות עם פרי מפוסל, עלים רכים ושרשרת שמחברת הכול יחד. בחרתי ורוד עדין וירוק של גינה, כדי לתת לאדום הקטן את כל הבמה.',images:['assets/strawberry.png','assets/strawberry-detail.png'],state:'published'},{id:'moon',title:'עד הירח. ובחזרה אליכם.',description:'רציתי לתפוס את הרגע השקט שבו מבקשים משאלה. יצרתי ירח בהיר, פיזרתי כוכבים בצבע חמאה ועטפתי את הכול בתכלת. כל קופסה היא עולם קטן, וכל פרט ממשיך את אותו חלום.',images:['assets/moon.png','assets/moon-detail.png'],state:'published'}];
let active=projects[0].id,draft,dirty=false,deleteId=null,invitationProject=null;
let testimonials=[{id:1,project:'strawberry',text:'כל פרט קטן היה כל כך יפה. הקופסאות נשארו אצל כולם כמזכרת מהחגיגה.',state:'pending'},{id:2,project:'moon',text:'הצלחת להפוך רעיון קטן למשהו מיוחד. הירח והכוכבים נראו נהדר ביחד.',state:'pending'},{id:3,project:'strawberry',text:'הצבעים, האריזה וההשקעה — היה ברור שהכול נעשה באהבה.',state:'published'}];
testimonials.push({id:4,project:'moon',text:'כל כוכב קטן הרגיש כמו מתנה בפני עצמו. נשאר לנו זיכרון יפה מהחגיגה.',state:'published'});
const labels={published:'מפורסם',draft:'טיוטה',archived:'בארכיון',pending:'ממתינה לאישור',private:'פרטית'};
function el(tag,cls,text){const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node}
function button(text,fn,cls=''){const b=el('button',cls,text);b.type='button';b.onclick=fn;return b}
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500)}
function saveDraftFields(){draft.title=$('#project-title').value;draft.description=$('#project-description').value}
function updateList(){const list=$('#project-items');list.replaceChildren();projects.forEach((p,index)=>{const item=el('div','project-item'+(p.id===active?' selected':''));const select=button('',()=>{if(dirty){saveDraftFields();projects.find(p=>p.id===active).working={...draft,images:[...draft.images]}}openProject(p.id)},'project-select');if(p.images.length)select.append(Object.assign(el('img'),{src:p.images[0],alt:''}));const info=el('div');info.append(el('strong','',p.title||'פרויקט חדש'),el('small','',`${labels[p.state]} · ${p.images.length} תמונות`));select.append(info);const order=el('div','project-order');for(const [offset,label]of[[-1,'↑ קודם'],[1,'↓ הבא']]){const b=button(label,()=>{[projects[index],projects[index+offset]]=[projects[index+offset],projects[index]];updateList();toast('סדר המגילה עודכן בהדגמה')});b.disabled=index+offset<0||index+offset>=projects.length;order.append(b)}item.append(select,order);list.append(item)});$('#project-count').textContent=`${projects.length} פרויקטים`;document.querySelector('[data-tab=projects] span').textContent=String(projects.length).padStart(2,'0')}
function openProject(id){active=id;const p=projects.find(p=>p.id===id);draft=structuredClone(p.working||p);dirty=!!p.working;$('#project-title').value=draft.title;$('#project-description').value=draft.description;$('#editor-title').textContent=p.title||'פרויקט חדש';$('#status').textContent=labels[p.state];$('#status').className='badge '+(p.state==='published'?'':p.state);$('#save-state').textContent=dirty?'שינויים בטיוטה המקומית':'הכול מוכן לעריכה';$('#publish').textContent=p.state==='published'?'פרסום שינויים':'פרסום במגילה';$('#archive').textContent=p.state==='archived'?'החזרה לטיוטה':'העברה לארכיון';updateList();renderMedia()}
function markDirty(){dirty=true;$('#save-state').textContent='יש שינויים שטרם נשמרו'}
function renderMedia(){const list=$('#media-list');list.replaceChildren();draft.images.forEach((src,i)=>{const tile=el('div','media-tile');tile.append(Object.assign(el('img'),{src,alt:`תמונה ${i+1} בפרויקט`}));const controls=el('div','media-controls');controls.append(el('span','',i===0?'תמונת כריכה':`תמונה ${i+1}`));const move=button('←',()=>{[draft.images[i],draft.images[i-1]]=[draft.images[i-1],draft.images[i]];markDirty();renderMedia()});move.disabled=i===0;move.setAttribute('aria-label',`העברת תמונה ${i+1} לתחילת האלבום`);controls.append(move,button('הסרה',()=>{draft.images.splice(i,1);markDirty();renderMedia()}));tile.append(controls);list.append(tile)});if(!draft.images.length)list.append(el('p','field-note','הוסיפי תמונה ראשונה כדי לתת לפרויקט פנים.'))}
$('#project-form').oninput=markDirty;$('#project-form').onsubmit=e=>{e.preventDefault();saveDraftFields();const p=projects.find(p=>p.id===active);p.working={...draft,images:[...draft.images]};dirty=false;$('#save-state').textContent='הטיוטה נשמרה להדגמה';toast('הטיוטה נשמרה בזיכרון ההדגמה. האתר הציבורי לא השתנה.')};
$('#publish').onclick=()=>{saveDraftFields();if(!draft.title.trim()||!draft.description.trim()||!draft.images.length){toast('צריך שם, תיאור ותמונה אחת כדי לפרסם');return}const p=projects.find(p=>p.id===active);Object.assign(p,{title:draft.title,description:draft.description,images:[...draft.images],state:'published'});delete p.working;openProject(active);toast('הפרויקט מסומן כמפורסם בהדגמה בלבד')};
$('#archive').onclick=()=>{const p=projects.find(p=>p.id===active);p.state=p.state==='archived'?'draft':'archived';openProject(active);toast('מצב הפרויקט עודכן בהדגמה')};
$('#new-project').onclick=()=>{const p={id:'sample-'+Date.now(),title:'פרויקט חדש',description:'',images:[],state:'draft'};projects.unshift(p);openProject(p.id);$('#project-title').focus()};
$('#upload').onchange=e=>{for(const file of e.target.files){if(file.type.startsWith('image/'))draft.images.push(URL.createObjectURL(file))}markDirty();renderMedia();e.target.value=''};
$('#preview').onclick=()=>{saveDraftFields();const frame=$('#preview-dialog iframe');frame.onload=()=>frame.contentWindow.postMessage({type:'wonder-preview',project:{title:draft.title,description:draft.description,image:draft.images[0],testimonials:testimonials.filter(t=>t.project===active&&t.state==='published').map(t=>t.text)}},location.origin);frame.src='index.html?ownerPreview=1#strawberry';$('#preview-dialog').showModal()};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#projects-panel').hidden=b.dataset.tab!=='projects';$('#testimonials-panel').hidden=b.dataset.tab!=='testimonials';if(b.dataset.tab==='testimonials')renderTestimonials()});
function renderTestimonials(){const list=$('#testimonial-list');list.replaceChildren();testimonials.forEach(t=>{const p=projects.find(p=>p.id===t.project);const card=el('article','testimonial');if(p.images[0])card.append(Object.assign(el('img'),{src:p.images[0],alt:''}));else card.append(el('span'));const content=el('div');content.append(el('h3','',p.title),el('span','badge '+(t.state==='published'?'':'draft'),labels[t.state]),el('blockquote','',t.text),el('small','','המלצה בדיונית להדגמת העיצוב · ללא פרטי לקוח'));const actions=el('div','testimonial-actions');actions.append(button(t.state==='published'?'ביטול פרסום':'פרסום המלצה',()=>{t.state=t.state==='published'?'private':'published';renderTestimonials();toast('מצב ההמלצה עודכן בהדגמה')},'outline'),button('מחיקה',()=>{deleteId=t.id;$('#delete-dialog').showModal()},'quiet'));card.append(content,actions);list.append(card)});const count=testimonials.filter(t=>t.state==='pending').length;$('.pending-count').textContent=count;$('#pending-summary').textContent=count?`${count} המלצות מחכות לך`:'אין המלצות שממתינות לאישור';if(!testimonials.length)list.append(el('p','','כאן יופיעו המילים הטובות שישלחו לך.'))}
$('#confirm-delete').onclick=()=>{testimonials=testimonials.filter(t=>t.id!==deleteId);$('#delete-dialog').close();renderTestimonials();toast('ההמלצה הוסרה מההדגמה')};
$('#invite').onclick=()=>{const select=$('#invite-project');select.replaceChildren();projects.forEach(p=>{const o=el('option','',p.title);o.value=p.id;select.append(o)});$('#invitation-result').hidden=true;$('#sample-testimonial').value='';$('#sample-testimonial').disabled=false;$('#submit-sample').disabled=false;$('#submit-sample').textContent='שליחת המלצה לדוגמה';$('#invite-dialog').showModal()};
$('#make-invite').onclick=()=>{invitationProject=$('#invite-project').value;$('#invitation-title').textContent=projects.find(p=>p.id===invitationProject).title;$('#invitation-result').hidden=false;$('#sample-testimonial').disabled=false;$('#sample-testimonial').value='';$('#submit-sample').disabled=false;$('#submit-sample').textContent='שליחת המלצה לדוגמה'};
$('#submit-sample').onclick=()=>{const value=$('#sample-testimonial').value.trim();if(!value){toast('כתבו כמה מילים לפני השליחה');return}testimonials.unshift({id:Date.now(),project:invitationProject,text:value,state:'pending'});$('#sample-testimonial').disabled=true;$('#submit-sample').disabled=true;$('#submit-sample').textContent='נשלח. ההזמנה נוצלה.';renderTestimonials();toast('המלצה חדשה ממתינה לאישור שלך בהדגמה')};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());openProject(active);
